name: "say hello"
description: "a simple github action"

inputs:
  name:
    description: "The name of the person"
    required: true

runs:
  using: "composite"
  steps:
    - run:  ./.github/actions/say-hello/hello.sh
      shell: bash