name: Demo custom action

on:
  push:
    branches: [main]
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run my custom greeting action
        uses: ./github/actions/say-hello
        with:
          name  

